
<div class="container " role="main">
<h1><?php echo $title; ?></h1>
<hr />


<div class="row">
  
  
<form class="cmxform" id="flightform" method="post" action="">
   <div class="col-md-6">
      <div class="panel panel-default">
      <div class="panel-heading">
      <h3 class="panel-title">Where do you want to go?</h3>
      </div>
      <div class="panel-body">
      <fieldset class="form-group">
        
        <p>
          <label for="fromflight">From Airport:</label>
          <input id="fromflight" name="from_flight" type="text" class="form-control">

        </p>
        <p>
          <label for="toflight">To Airport:</label>
          <input id="toflight" name="to_flight" type="text" class="form-control">

        </p>
        </fieldset>
      </div>
      </div>
    </div>

    <div class="col-md-6">
     <div class="panel panel-default">
      <div class="panel-heading">
      <h3 class="panel-title">When do you want to go?</h3>
      </div>
      <div class="panel-body">
      <fieldset class="form-group">
        <p id="datepairExample">
            <input type="text" class="date start" />
            <input type="text" class="time start" /> to
            <input type="text" class="time end" />
            <input type="text" class="date end" />
        </p>

           
      </fieldset>

      </div>
      </div>  
      <p>
        <label for="passengers"># Of Passengers:</label>
        <input id="passengers" name="passengers" type="text" class="form-control">

      </p>
      <p>
        <label for="directflight">Direct Flights Only:</label>
        <input id="directflight" name="directflight" type="checkbox" class="form-control">
      </p>

      <p>
        <button type="submit" value="submit" name="submit" id="submit" class="btn btn-primary">Submit</button>
      </p>
    </fieldset>
    </div>
  </form>
</div>
 <script>
    $('#datepairExample .time').timepicker({
    'showDuration': true,
    'timeFormat': 'g:ia'
    });

    $('#datepairExample .date').datepicker({
    'format': 'm/d/yyyy',
    'autoclose': true
    });

    $('#datepairExample').datepair();
    </script>

            
  <script>
  $().ready(function() {
       // validate signup form on keyup and submit
    $("#flightform").validate({
      rules: {
        fromflight: "required",
        toflight: "required",
        username: {
          required: true,
          minlength: 2
        },
        password: {
          required: true,
          minlength: 5
        },
        confirm_password: {
          required: true,
          minlength: 5,
          equalTo: "#password"
        },
        email: {
          required: true,
          email: true
        },
        topic: {
          required: "#newsletter:checked",
          minlength: 2
        },
        agree: "required"
      },
      messages: {
        firstname: "Please enter your firstname",
        lastname: "Please enter your lastname",
        username: {
          required: "Please enter a username",
          minlength: "Your username must consist of at least 2 characters"
        },
        password: {
          required: "Please provide a password",
          minlength: "Your password must be at least 5 characters long"
        },
        confirm_password: {
          required: "Please provide a password",
          minlength: "Your password must be at least 5 characters long",
          equalTo: "Please enter the same password as above"
        },
        email: "Please enter a valid email address",
        agree: "Please accept our policy",
        topic: "Please select at least 2 topics"
      }
    });

    // propose username by combining first- and lastname
    $("#username").focus(function() {
      var firstname = $("#firstname").val();
      var lastname = $("#lastname").val();
      if (firstname && lastname && !this.value) {
        this.value = firstname + "." + lastname;
      }
    });
  });
  </script>
</div> <!-- /container -->