<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="assets/favicon.ico">

    <title><?php echo $title; ?> | Our Service</title>

    <!-- Bootstrap core CSS -->
    <link href="assets/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="assets/css/bootstrap-theme.min.css" rel="stylesheet">
     <!-- Sticky Footer -->
    <link href="assets/css/sticky-footer.css" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="assets/css/theme.css" rel="stylesheet">
    <!-- Validation & jquery -->
    <script src="assets/js/jquery-2.2.0.js"></script>
    <script src="assets/js/jquery.validate.js"></script>
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="assets/cssassets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="assets/js/ie-emulation-modes-warning.js"></script>


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
  </head>
  <body role="document">

    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Our Service</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <?php if(isset($_SESSION['id'])) { ?>
            <li <?php if ($title=="Home") { echo 'class="active"';} ?>><a href="main.php">Home</a></li>
            <li <?php if ($title=="Check In") { echo 'class="active"';} ?>><a href="check_in.php">Check In</a></li>
            <li <?php if ($title=="Check Flights") { echo 'class="active"';} ?>><a href="check_flights.php">Check Flights</a></li>
            <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account <span class="caret"></span></a>
              <ul class="dropdown-menu">
              <li  <?php if ($title=="My Account") { echo 'class="active"';} ?>><a href="account.php"><?php echo $user->getFirst_name() . "'s Settings"; ?></a></li>
              <li role="separator" class="divider"></li>
              <li <?php if ($title=="Logout") { echo 'class="active"';} ?>><a href="logout.php">Logout</a></li>
              
              </ul>
              </li>



            <?php } else { ?>
            <li>hello</li>
            <li <?php if ($title=="Home") { echo 'class="active"';} ?>><a href="index.php">Home</a></li>
            <li <?php if ($title=="Register") { echo 'class="active"';} ?>><a href="register.php">Register</a></li>
            <li <?php if ($title=="Login") { echo 'class="active"';} ?>><a href="login.php">Login</a></li>
            <?php } ?>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

