<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="assets/favicon.ico">

    <title><?php echo $title; ?> | Our Service</title>

    <!-- Bootstrap core CSS -->
    <link href="assets/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="assets/css/bootstrap-theme.css" rel="stylesheet">
     <!-- Sticky Footer -->
    <link hr3ef="assets/css/sticky-footer.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="assets/css/theme.css" rel="stylesheet">
    <!-- Validation & jquery -->
    <script src="assets/js/jquery-2.2.0.js"></script>
    <script src="assets/js/jquery.validate.js"></script>
    <!--Picker-->

    <script type="text/javascript" src="assets/lib/bootstrap-datepicker.js"></script>
    <link rel="stylesheet" type="text/css" href="assets/lib/bootstrap-datepicker.css" />

    <script type="text/javascript" src="assets/lib/site.js"></script>


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
  </head>
  <body role="document">

    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" style="text-transform:uppercase;"><span class="glyphicon glyphicon-plane"></span> Project Air</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-left">
            <?php if(isset($_SESSION['id'])) { ?>
          <li <?php if ($title=="Home") { echo 'class="active"';} ?>><a href="main.php">Home</a></li>
            <li <?php if ($title=="Book a flight") { echo 'class="active"';} ?>><a href="book_a_flight.php">Book Flight</a></li>
            <li <?php if ($title=="Check Flights") { echo 'class="active"';} ?>><a href="check_flights.php">Check Flight</a></li>
            <?php } ?>
          </ul>
    <ul class="nav navbar-nav navbar-right">
       <?php if(isset($_SESSION['id'])) { ?>
       <li><a>Welcome <?php echo $user->getFirst_name(); ?> </a> </li>
       <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-globe"></span> Settings<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="settings.php"><span class="glyphicon glyphicon-user"></span> My Account</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="logout.php"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
          </ul>
        </li>
        <?php } else { ?>
      <li><a href="register.php"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="login.php"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      <?php } ?>
    </ul>
        </div><!--/.nav-collapse -->

      </div>
    </nav>

