
    <div class="container theme-showcase" role="main">
    	<div class="col-md-9">
      <!-- Main banner our service -->
      <div class="jumbotron">
        <h1><?php echo $company_name ?></h1>
        <p>We provide a register and login facility</p>
      </div>
  </div>
  <div class="col-md-3">
  	      <div class="panel panel-default">
      <div class="panel-heading">
      <h3 class="panel-title">Login</h3>
      </div>
      <div class="panel-body">
        <form method="post" action="">
      <fieldset class="form-group">
                  
            <label for="username">Username:</label>
            <input type="text" name="username" class="form-control"/>
            <label for="password">Password:</label>
            <input type="password" name="password" class="form-control"/><br>
 			<button style="float:right" type="submit" value="submit" name="login" id="submit" class="btn btn-primary">Login</button>
           
      </fieldset>
    </form>
      </div>
      </div>  
    
    </div>


    </div> <!-- /container -->