<div class="container " role="main">
<h1><?php echo $title; ?></h1>
<hr />

<form class="cmxform" id="signupForm" method="post" action="">
    <fieldset class="form-group">
      <p>
        <label for="firstname">Firstname</label>
        <input id="firstname" name="first_name" type="text" class="form-control">

      </p>
      <p>
        <label for="lastname">Lastname</label>
        <input id="lastname" name="last_name" type="text" class="form-control">

      </p>
      <p>
        <label for="email">Email</label>
        <input id="email" name="email" type="email" class="form-control">

      </p>
      <p>
        <label for="username">Username</label>
        <input id="username" name="username" type="text" class="form-control">

      </p>
      <p>
        <label for="password">Password</label>
        <input id="password" name="password" type="password" class="form-control">
     
      </p>
      <p>
        <label for="confirm_password">Confirm password</label>
        <input id="confirm_password" name="confirm_password" type="password" class="form-control">
      </p>

      <p>
        <button type="submit" value="submit" name="submit" id="submit" class="btn btn-primary">Submit</button>
      </p>
    </fieldset>
  </form>
  <script>
  $().ready(function() {
       // validate signup form on keyup and submit
    $("#signupForm").validate({
      rules: {
        firstname: "required",
        lastname: "required",
        username: {
          required: true,
          minlength: 2
        },
        password: {
          required: true,
          minlength: 5
        },
        confirm_password: {
          required: true,
          minlength: 5,
          equalTo: "#password"
        },
        email: {
          required: true,
          email: true
        },
        topic: {
          required: "#newsletter:checked",
          minlength: 2
        },
        agree: "required"
      },
      messages: {
        firstname: "Please enter your firstname",
        lastname: "Please enter your lastname",
        username: {
          required: "Please enter a username",
          minlength: "Your username must consist of at least 2 characters"
        },
        password: {
          required: "Please provide a password",
          minlength: "Your password must be at least 5 characters long"
        },
        confirm_password: {
          required: "Please provide a password",
          minlength: "Your password must be at least 5 characters long",
          equalTo: "Please enter the same password as above"
        },
        email: "Please enter a valid email address",
        agree: "Please accept our policy",
        topic: "Please select at least 2 topics"
      }
    });

    // propose username by combining first- and lastname
    $("#username").focus(function() {
      var firstname = $("#firstname").val();
      var lastname = $("#lastname").val();
      if (firstname && lastname && !this.value) {
        this.value = firstname + "." + lastname;
      }
    });
  });
  </script>
</div> <!-- /container -->
